- name: Nginx Example
  hosts: all
  tasks:
    - name: deploy public key JFA
      authorized_key:
        key: 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIRAzjzasfdfp6sRL9fJgTufLy0TbnQs/YR6di0iIpd3lhebLgoT8JFdVoijNlK7vENGoAUW1IeUPJilpEaCVF0= jfader@fader-t510'
        user: core

    - name: Start docker
      become: True
      service:
        name: docker
        state: started

    - name: "copy docker-compose-files"
      copy:
        dest: /tmp
        src: files

    - name: launch traefik container
      docker_service:
        project_src: /tmp/files/traefik
        restarted: true
        state: present

    - name: start two whoami containers
      docker_service:
        project_src: /tmp/files/test
        scale:
          whoami: 2
        state: present
